import:
  module: "mysql"
  parameters:
    hostname: "localhost"
    port-number: "3306"
    username: "root"
    password: "123456"
    database: "sakila"
schemas:
  sakila:
    custom:
      - name: "custom_view_example"
        description: "this is an example for a custom view configuration"
        query: "select * from actor"
    tables:
    - name: "actor"
      columns:
      - name: "actor_id"
      - name: "first_name"
      - name: "last_name"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "address"
      columns:
      - name: "address_id"
      - name: "address"
      - name: "address2"
      - name: "district"
      - name: "city_id"
      - name: "postal_code"
      - name: "phone"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "category"
      columns:
      - name: "category_id"
      - name: "name"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "city"
      columns:
      - name: "city_id"
      - name: "city"
      - name: "country_id"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "country"
      columns:
      - name: "country_id"
      - name: "country"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "customer"
      columns:
      - name: "customer_id"
      - name: "store_id"
      - name: "first_name"
      - name: "last_name"
      - name: "email"
      - name: "address_id"
      - name: "active"
      - name: "create_date"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "film"
      columns:
      - name: "film_id"
      - name: "title"
      - name: "description"
      - name: "release_year"
      - name: "language_id"
      - name: "original_language_id"
      - name: "rental_duration"
      - name: "rental_rate"
      - name: "length"
      - name: "replacement_cost"
      - name: "rating"
      - name: "special_features"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "film_actor"
      columns:
      - name: "actor_id"
      - name: "film_id"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "film_category"
      columns:
      - name: "film_id"
      - name: "category_id"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "film_text"
      columns:
      - name: "film_id"
      - name: "title"
      - name: "description"
      where: ""
      orderBy: ""
    - name: "inventory"
      columns:
      - name: "inventory_id"
      - name: "film_id"
      - name: "store_id"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "language"
      columns:
      - name: "language_id"
      - name: "name"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "payment"
      columns:
      - name: "payment_id"
      - name: "customer_id"
      - name: "staff_id"
      - name: "rental_id"
      - name: "amount"
      - name: "payment_date"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "rental"
      columns:
      - name: "rental_id"
      - name: "rental_date"
      - name: "inventory_id"
      - name: "customer_id"
      - name: "return_date"
      - name: "staff_id"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "staff"
      columns:
      - name: "staff_id"
      - name: "first_name"
      - name: "last_name"
      - name: "address_id"
      - name: "picture"
      - name: "email"
      - name: "store_id"
      - name: "active"
      - name: "username"
      - name: "password"
      - name: "last_update"
      where: ""
      orderBy: ""
    - name: "store"
      columns:
      - name: "store_id"
      - name: "manager_staff_id"
      - name: "address_id"
      - name: "last_update"
      where: ""
      orderBy: ""
    views:
    - name: "actor_info"
      materialized: false
      columns:
      - "actor_id"
      - "first_name"
      - "last_name"
      - "film_info"
      where: ""
      orderBy: ""
    - name: "customer_list"
      materialized: false
      columns:
      - "ID"
      - "name"
      - "address"
      - "zip code"
      - "phone"
      - "city"
      - "country"
      - "notes"
      - "SID"
      where: ""
      orderBy: ""
    - name: "film_list"
      materialized: false
      columns:
      - "FID"
      - "title"
      - "description"
      - "category"
      - "price"
      - "length"
      - "rating"
      - "actors"
      where: ""
      orderBy: ""
    - name: "nicer_but_slower_film_list"
      materialized: false
      columns:
      - "FID"
      - "title"
      - "description"
      - "category"
      - "price"
      - "length"
      - "rating"
      - "actors"
      where: ""
      orderBy: ""
    - name: "sales_by_film_category"
      materialized: false
      columns:
      - "category"
      - "total_sales"
      where: ""
      orderBy: ""
    - name: "sales_by_store"
      materialized: false
      columns:
      - "store"
      - "manager"
      - "total_sales"
      where: ""
      orderBy: ""
    - name: "staff_list"
      materialized: false
      columns:
      - "ID"
      - "name"
      - "address"
      - "zip code"
      - "phone"
      - "city"
      - "country"
      - "SID"
      where: ""
      orderBy: ""
ignore:
  users: false
  roles: false
  privileges: false
  routines: false
  triggers: false
  primaryKeys: false
  candidateKeys: false
  foreignKeys: false
  checkConstraints: false
  views: false
